# Generated by Django 3.0.3 on 2020-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', 'add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementcategory',
            name='necessarily_paying',
            field=models.BooleanField(default=False, verbose_name='Обязательна к выплате'),
        ),
    ]
