# Generated by Django 3.0.3 on 2020-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200506_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementcategory',
            name='maximum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Максимальная выплата'),
        ),
        migrations.AlterField(
            model_name='statementcategory',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Приоритет'),
        ),
    ]
