# Generated by Django 3.0.3 on 2020-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200515_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementcategory',
            name='legal_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Юридический номер'),
        ),
    ]
