# Generated by Django 3.0.3 on 2020-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200520_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementcategory',
            name='legal_number',
            field=models.CharField(max_length=50, verbose_name='Юридический номер'),
        ),
    ]
