# Generated by Django 3.0.3 on 2020-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200520_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='student_middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
