# Generated by Django 3.0.3 on 2020-05-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20200520_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='student_group',
        ),
    ]
