# Generated by Django 3.0.3 on 2020-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_statement_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementcategory',
            name='necessarily_paying',
        ),
        migrations.AddField(
            model_name='statementcategory',
            name='month_payment',
            field=models.BooleanField(default=False, verbose_name='Ежемесячная выплата'),
        ),
    ]
