# Generated by Django 3.0.3 on 2020-06-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_initial', models.CharField(blank=True, max_length=100, verbose_name='Инициалы студента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма выплаты')),
                ('date', models.DateField(verbose_name='Дата выплаты')),
                ('statement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='crud.Statement', verbose_name='Заявление')),
                ('statement_category', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crud.StatementCategory', verbose_name='Категория выплаты')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
    ]
