# Generated by Django 3.0.3 on 2020-05-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', 'restore_anonymous_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
