# Generated by Django 3.0.3 on 2020-05-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200515_1520'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='statement_category',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crud.StatementCategory', verbose_name='Категория выплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='crud.Statement', verbose_name='Заявление'),
        ),
    ]
