# Generated by Django 3.0.3 on 2020-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200227_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=50, verbose_name='Пол'),
        ),
    ]
