# Generated by Django 3.0.3 on 2020-02-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200228_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='student_category',
            new_name='statement_category',
        ),
    ]
