# Generated by Django 3.0.3 on 2020-02-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200229_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='studying_type',
            new_name='studying_level',
        ),
    ]
