# Generated by Django 3.0.3 on 2020-02-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200229_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_chief',
        ),
    ]
