# Generated by Django 3.0.3 on 2020-03-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_student_is_chief'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_card_id',)},
        ),
    ]
