# Generated by Django 3.0.3 on 2020-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200302_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='studying_level',
            field=models.CharField(choices=[('under', 'Бакалавриат'), ('graduated', 'Магистратура'), ('specialist', 'Специалитет'), ('post', 'Аспирантура')], max_length=50, verbose_name='Ступень обучения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
