# Generated by Django 3.0.3 on 2020-03-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200303_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement', to='main.StatementCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
